serverAddr = "ec2-13-212-186-72.ap-southeast-1.compute.amazonaws.com"
serverPort = 7000

[[proxies]]
name = "@@DEVICE_ID@@_http_proxy"
type = "tcp"
localPort = 10080

[[proxies]]
name = "@@DEVICE_ID@@_socks_proxy"
type = "tcp"
localPort = 1080